/**
 * DEVELOPMENT/TEST HELPER: prints a fresh Ed25519 identity in the plugin's identity.json
 * format ({ server_id, private_key_seed_b64, public_key_b64, fingerprint, created_at }).
 * Real servers generate their key inside the plugin; a private key must never be created
 * or stored elsewhere for production use (R9).
 *
 *   pnpm exec tsx src/cli/generate-keypair.ts [--server-id srv_…]
 */
import { parseArgs } from 'node:util';

import { generateIdentity } from './support/identity';

function main(): number {
  const { values } = parseArgs({
    args: process.argv.slice(2).filter((arg) => arg !== '--'),
    options: { 'server-id': { type: 'string' }, help: { type: 'boolean', short: 'h' } },
    strict: true,
  });
  if (values.help === true) {
    process.stdout.write('Usage: generate-keypair [--server-id srv_…]   (testing only)\n');
    return 0;
  }
  process.stderr.write('WARNING: test identity only. Production keys are generated by the plugin on the SCP:SL server.\n');
  process.stdout.write(`${JSON.stringify(generateIdentity(values['server-id'] ?? null), null, 2)}\n`);
  return 0;
}

try {
  process.exitCode = main();
} catch (err) {
  process.stderr.write(`error: ${err instanceof Error ? err.message : String(err)}\n`);
  process.exitCode = 1;
}
