/**
 * Column manifest of the database schema, generated once from the migrated
 * schema and kept in sync by two independent checks:
 *  - compile time: `satisfies SchemaManifest` fails if any entry disagrees with
 *    src/db/types.ts (missing/extra column, kind, nullability, insert optionality);
 *  - runtime: schema-manifest.test.ts compares it with information_schema.
 * Together they prove that the Kysely Database interface matches the SQL.
 *
 * Entry: [kind, nullable, optional on insert (nullable or has a DB default)].
 */
import type { InsertType, SelectType } from 'kysely';

import type { Database } from '../../src/db/types';

export type ColumnKind = 'string' | 'number' | 'boolean' | 'date' | 'string[]' | 'json';

type KindOf<T> = [T] extends [Date]
  ? 'date'
  : [T] extends [readonly string[]]
    ? 'string[]'
    : [T] extends [string]
      ? 'string'
      : [T] extends [number]
        ? 'number'
        : [T] extends [boolean]
          ? 'boolean'
          : [T] extends [Record<string, unknown>]
            ? 'json'
            : never;
type IsNullable<T> = null extends T ? true : false;
// A column that can never be inserted (update-only) must be nullable or defaulted in SQL.
type IsOptionalInsert<T> = [T] extends [never] ? true : undefined extends T ? true : null extends T ? true : false;
type ColumnSpec<C> = readonly [
  KindOf<NonNullable<SelectType<C>>>,
  IsNullable<SelectType<C>>,
  IsOptionalInsert<InsertType<C>>,
];

export type SchemaManifest = {
  readonly [T in keyof Database]: { readonly [K in keyof Database[T]]-?: ColumnSpec<Database[T][K]> };
};

export const SCHEMA_MANIFEST = {
  appeals: {
    id: ['string', false, true],
    case_id: ['string', false, false],
    player_id: ['string', false, false],
    submitted_by_user_id: ['string', false, false],
    statement: ['string', false, false],
    status: ['string', false, true],
    assigned_reviewer_id: ['string', true, true],
    decision: ['string', true, true],
    decision_reason: ['string', true, true],
    decided_by: ['string', true, true],
    decided_at: ['date', true, true],
    conflict_override: ['boolean', false, true],
    created_at: ['date', false, true],
    updated_at: ['date', false, true],
  },
  audit_events: {
    seq: ['number', false, false],
    event_id: ['string', false, false],
    created_at: ['date', false, false],
    actor_type: ['string', false, false],
    actor_id: ['string', true, true],
    action: ['string', false, false],
    target_type: ['string', false, false],
    target_id: ['string', true, true],
    server_id: ['string', true, true],
    case_id: ['string', true, true],
    metadata: ['json', false, true],
    request_id: ['string', true, true],
    prev_hash: ['string', false, false],
    hash: ['string', false, false],
  },
  bypasses: {
    id: ['string', false, true],
    player_id: ['string', false, false],
    scope: ['string', false, false],
    server_id: ['string', true, true],
    type: ['string', false, false],
    reason: ['string', false, false],
    granted_by_user_id: ['string', false, false],
    whitelist_request_id: ['string', true, true],
    created_at: ['date', false, true],
    expires_at: ['date', true, true],
    revoked_at: ['date', true, true],
    revoked_by: ['string', true, true],
    revoke_reason: ['string', true, true],
    expired_processed_at: ['date', true, true],
  },
  case_counters: {
    year: ['number', false, false],
    last_value: ['number', false, false],
  },
  case_server_confirmations: {
    id: ['string', false, true],
    case_id: ['string', false, false],
    server_id: ['string', false, false],
    confirmed_by_user_id: ['string', false, false],
    note: ['string', true, true],
    created_at: ['date', false, true],
    revoked_at: ['date', true, true],
    revoked_by: ['string', true, true],
    revoke_reason: ['string', true, true],
  },
  cases: {
    id: ['string', false, true],
    case_number: ['string', false, false],
    player_id: ['string', false, false],
    current_verdict: ['string', false, true],
    status: ['string', false, true],
    reason: ['string', false, false],
    public_summary: ['string', true, true],
    created_by_user_id: ['string', true, true],
    created_by_server_id: ['string', true, true],
    verdict_set_by: ['string', true, true],
    verdict_set_at: ['date', true, true],
    closed_at: ['date', true, true],
    created_at: ['date', false, true],
    updated_at: ['date', false, true],
  },
  evidence: {
    id: ['string', false, true],
    case_id: ['string', false, false],
    report_id: ['string', true, true],
    type: ['string', false, false],
    title: ['string', false, false],
    description: ['string', true, true],
    status: ['string', false, true],
    identity_status: ['string', false, true],
    authenticity_status: ['string', false, true],
    cheating_status: ['string', false, true],
    sha256: ['string', true, true],
    size_bytes: ['number', true, true],
    mime_type: ['string', true, true],
    original_filename: ['string', true, true],
    storage_key: ['string', true, true],
    external_url: ['string', true, true],
    uploaded_at: ['date', false, true],
    uploader_user_id: ['string', true, true],
    uploader_server_id: ['string', true, true],
    overwatch_session_id: ['string', true, true],
    supersedes_evidence_id: ['string', true, true],
    superseded_by_evidence_id: ['string', true, true],
    created_at: ['date', false, true],
    updated_at: ['date', false, true],
  },
  evidence_reviews: {
    id: ['string', false, true],
    evidence_id: ['string', false, false],
    reviewer_user_id: ['string', false, false],
    status: ['string', false, false],
    identity_status: ['string', false, false],
    authenticity_status: ['string', false, false],
    cheating_status: ['string', false, false],
    comment: ['string', false, false],
    created_at: ['date', false, true],
  },
  job_runs: {
    id: ['string', false, true],
    job: ['string', false, false],
    started_at: ['date', false, true],
    finished_at: ['date', true, true],
    result: ['string', false, true],
    details: ['json', false, true],
  },
  overwatch_sessions: {
    id: ['string', false, true],
    server_id: ['string', false, false],
    target_player_id: ['string', false, false],
    spectator_player_id: ['string', false, false],
    secret_enc: ['string', true, true],
    interval_seconds: ['number', false, true],
    status: ['string', false, true],
    started_at: ['date', false, false],
    ended_at: ['date', true, true],
    last_heartbeat_at: ['date', false, false],
    end_reason: ['string', true, true],
    created_at: ['date', false, true],
  },
  player_links: {
    id: ['string', false, true],
    player_id: ['string', false, false],
    linked_player_id: ['string', false, false],
    signal: ['string', false, false],
    first_detected_at: ['date', false, true],
    last_detected_at: ['date', false, true],
    occurrences: ['number', false, true],
  },
  player_network_observations: {
    id: ['string', false, true],
    player_id: ['string', false, false],
    network_hash: ['string', false, false],
    prefix_hash: ['string', false, false],
    server_id: ['string', false, false],
    first_seen_at: ['date', false, true],
    last_seen_at: ['date', false, true],
    seen_count: ['number', false, true],
  },
  player_server_sightings: {
    player_id: ['string', false, false],
    server_id: ['string', false, false],
    first_seen_at: ['date', false, true],
    last_seen_at: ['date', false, true],
    join_count: ['number', false, true],
  },
  player_signals: {
    id: ['string', false, true],
    player_id: ['string', false, false],
    server_id: ['string', true, true],
    signal: ['string', false, false],
    confidence: ['string', true, true],
    source: ['string', false, false],
    detail_codes: ['string[]', false, true],
    created_at: ['date', false, true],
    expires_at: ['date', true, true],
  },
  players: {
    id: ['string', false, true],
    id_type: ['string', false, false],
    external_id: ['string', false, false],
    display_name: ['string', true, true],
    first_seen_at: ['date', true, true],
    last_seen_at: ['date', true, true],
    account_created_at: ['date', true, true],
    account_age_source: ['string', false, true],
    account_age_checked_at: ['date', true, true],
    created_at: ['date', false, true],
    updated_at: ['date', false, true],
  },
  reports: {
    id: ['string', false, true],
    case_id: ['string', false, false],
    player_id: ['string', false, false],
    server_id: ['string', true, true],
    reporter_type: ['string', false, false],
    reporter_user_id: ['string', true, true],
    reporter_player_id: ['string', true, true],
    reason: ['string', false, false],
    description: ['string', true, true],
    status: ['string', false, true],
    resolution_note: ['string', true, true],
    resolved_by: ['string', true, true],
    resolved_at: ['date', true, true],
    created_at: ['date', false, true],
    updated_at: ['date', false, true],
  },
  reviews: {
    id: ['string', false, true],
    case_id: ['string', false, false],
    reviewer_user_id: ['string', false, false],
    kind: ['string', false, false],
    previous_verdict: ['string', true, true],
    new_verdict: ['string', true, true],
    comment: ['string', false, false],
    appeal_id: ['string', true, true],
    created_at: ['date', false, true],
  },
  server_keys: {
    id: ['string', false, true],
    server_id: ['string', false, false],
    public_key: ['string', false, false],
    fingerprint: ['string', false, false],
    status: ['string', false, true],
    created_at: ['date', false, true],
    activated_at: ['date', false, true],
    retiring_until: ['date', true, true],
    retired_at: ['date', true, true],
    revoked_at: ['date', true, true],
    revoked_by: ['string', true, true],
    revoke_reason: ['string', true, true],
  },
  server_members: {
    server_id: ['string', false, false],
    user_id: ['string', false, false],
    role: ['string', false, false],
    created_at: ['date', false, true],
    created_by: ['string', false, false],
  },
  server_policies: {
    id: ['string', false, true],
    server_id: ['string', false, false],
    version: ['number', false, false],
    is_active: ['boolean', false, false],
    backend_unavailable_action: ['string', false, true],
    notify_on_enforcement: ['boolean', false, true],
    honor_global_bypasses: ['boolean', false, true],
    whitelist_url: ['string', true, true],
    created_by: ['string', true, true],
    created_at: ['date', false, true],
  },
  server_policy_rules: {
    id: ['string', false, true],
    policy_id: ['string', false, false],
    sort_order: ['number', false, false],
    enabled: ['boolean', false, true],
    signal: ['string', false, false],
    action: ['string', false, false],
    statuses: ['string[]', true, true],
    min_confirmed_servers: ['number', true, true],
    max_account_age_days: ['number', true, true],
    match_unknown_age: ['boolean', true, true],
    min_vpn_confidence: ['string', true, true],
    min_alt_confidence: ['string', true, true],
    require_linked_confirmed_case: ['boolean', true, true],
    min_open_reports: ['number', true, true],
    message: ['string', true, true],
    ban_duration_minutes: ['number', true, true],
  },
  server_registration_tokens: {
    id: ['string', false, true],
    server_id: ['string', false, false],
    token_hash: ['string', false, false],
    created_by: ['string', false, false],
    expires_at: ['date', false, false],
    used_at: ['date', true, true],
    revoked_at: ['date', true, true],
    created_at: ['date', false, true],
  },
  servers: {
    id: ['string', false, true],
    server_id: ['string', false, false],
    name: ['string', false, false],
    description: ['string', true, true],
    owner_user_id: ['string', false, false],
    status: ['string', false, true],
    is_trusted: ['boolean', false, true],
    accepts_whitelist_requests: ['boolean', false, true],
    plugin_version: ['string', true, true],
    game_version: ['string', true, true],
    last_seen_at: ['date', true, true],
    key_rotation_requested_at: ['date', true, true],
    registered_at: ['date', true, true],
    created_at: ['date', false, true],
    updated_at: ['date', false, true],
  },
  sessions: {
    id: ['string', false, true],
    user_id: ['string', false, false],
    token_hash: ['string', false, false],
    mfa_verified: ['boolean', false, false],
    created_at: ['date', false, true],
    last_seen_at: ['date', false, true],
    expires_at: ['date', false, false],
    idle_expires_at: ['date', false, false],
    revoked_at: ['date', true, true],
    revoked_reason: ['string', true, true],
    user_agent: ['string', true, true],
    ip_hash: ['string', true, true],
  },
  user_recovery_codes: {
    id: ['string', false, true],
    user_id: ['string', false, false],
    code_hash: ['string', false, false],
    used_at: ['date', true, true],
    created_at: ['date', false, true],
  },
  user_tokens: {
    id: ['string', false, true],
    user_id: ['string', false, false],
    type: ['string', false, false],
    token_hash: ['string', false, false],
    expires_at: ['date', false, false],
    used_at: ['date', true, true],
    created_at: ['date', false, true],
  },
  users: {
    id: ['string', false, true],
    email: ['string', false, false],
    username: ['string', false, false],
    password_hash: ['string', false, false],
    role: ['string', false, true],
    status: ['string', false, true],
    email_verified_at: ['date', true, true],
    failed_login_count: ['number', false, true],
    locked_until: ['date', true, true],
    totp_secret_enc: ['string', true, true],
    totp_enabled_at: ['date', true, true],
    totp_last_used_step: ['number', true, true],
    reviewer_number: ['number', true, true],
    player_id: ['string', true, true],
    last_login_at: ['date', true, true],
    created_at: ['date', false, true],
    updated_at: ['date', false, true],
  },
  whitelist_requests: {
    id: ['string', false, true],
    player_id: ['string', false, false],
    requester_user_id: ['string', false, false],
    server_id: ['string', false, false],
    type: ['string', false, false],
    reason: ['string', false, false],
    requested_days: ['number', true, true],
    status: ['string', false, true],
    decided_by: ['string', true, true],
    decided_at: ['date', true, true],
    decision_note: ['string', true, true],
    bypass_id: ['string', true, true],
    expires_at: ['date', false, false],
    created_at: ['date', false, true],
    updated_at: ['date', false, true],
  },
  schema_migrations: {
    version: ['string', false, false],
    checksum: ['string', false, false],
    applied_at: ['date', false, true],
  },
} as const satisfies SchemaManifest;
